### ISSUE TITLE
Error when permanently deleting a post

### ISSUE THREAD

**Issue by LuckVintage** [FriendsOfFlarum/gamification#31]
Hello there,

As long as I can remember I have always had a little pop-up error message (below) when attempting to permanently delete a post. The post appears to delete perfectly fine, but an error message is received.

<img width="350" alt="raw" src="https://user-images.githubusercontent.com/54641441/106938659-32419680-6717-11eb-9936-29ed854e1203.png">

Today I installed and set-up Sentry using the fof/Sentry extension and a new issue is automatically created in Sentry whenever I try to delete a post forever:

**Symfony\Component\Debug\Exception\FatalThrowableError**
`Argument 1 passed to FoF\Gamification\Listeners\RemoveVoteHandler::handle() must be an instance of Flarum\Post\Event\Deleting, instance of Flarum\Post\Event\Deleted given, called in /var/www/html/flarum/vendor/illuminate/events/Dispatcher.php on line 389`

I created a support post on the Flarum forum about this, and was advised to report this as an issue on your Github. (https://discuss.flarum.org/d/26138-error-when-permanently-deleting-a-post)

Many Thanks.

**Comment by clarkwinkelmann** [comment]
Definitely something we want to take a look at soon. It shouldn't be too difficult to fix too.

This line uses `Deleted` event https://github.com/FriendsOfFlarum/gamification/blob/131425e280fc4aa0e42af8548b2528bc3921d3a4/extend.php#L162

While this line uses `Deleting` https://github.com/FriendsOfFlarum/gamification/blob/131425e280fc4aa0e42af8548b2528bc3921d3a4/src/Listeners/RemoveVoteHandler.php#L20

I think `Deleted` is the one that makes the most sense, since another extension could still cancel the deletion in `Deleting`, while `Deleted` happens after it was already deleted for sure.

**Comment by Ralkage** [comment]
Pushed the fix as @clarkwinkelmann pointed out ;) I'll tag a patch release shortly.
