### ISSUE TITLE
No foreign key between post_votes and users table

### ISSUE THREAD

**Issue by rob006** [FriendsOfFlarum/gamification#87]
Is it intentional that there are no FK between these two tables? Right now if user gets deleted his votes are preserved and I'm not sure if it is expected behavior.

**Comment by clarkwinkelmann** [comment]
I think this might be intentional.

The hotness of discussions is calculated from that table, so deleting a user would cause a discussion to drop in the hotness ranking.

https://github.com/FriendsOfFlarum/gamification/blob/54db432e0e2162d11b4e579cb0567c47aad13aea/src/Vote.php#L77-L82

We should probably clarify that it is the intended behavior in the source code if we are ok with this.

**Comment by rob006** [comment]
I think that there should be FK with `SET NULL` for `ON DELETE` - it will be clear that this is intended behavior. Right now leaving orphaned IDs in `user_id` looks like an oversight.

**Comment by clarkwinkelmann** [comment]
That makes sense :+1:

**Comment by imorland** [comment]
Fixed in https://github.com/FriendsOfFlarum/gamification/pull/93
